### ISSUE TITLE
ERROR: Error getting package versions

### ISSUE THREAD

**Issue by salmankazmi** [wallabyjs/dingo#12]
I have installed Dingo recently on VS Code as an entension. Opening it with CMD + Shift + P -> Dingo Open.
Typing any library name shows this error in red:

ERROR: Error getting package versions

This is happening for all packages I am trying.

**Comment by smcenlly** [comment]
It is working for me. Can you confirm that you're still having problems?

Dingo is using `npm view ${packageName} repository --json` to retrieve the list of package versions ([see here](https://github.com/wallabyjs/dingo/blob/master/src/npm.ts#L70)). Can you try running this from the command-line to see if it works for you?

I have improved the error reporting for any errors so you should also get more detail in the VS Code Developer Tools console if you get the error again after updating Dingo to `v1.0.11`.

**Comment by salmankazmi** [comment]
Checked the debug console. It was complaining about unavailability of npm. I had installed it using brew/nvm. Somehow it wasn't available on the path. Reinstalled it. This fixed the issue. Thanks!
