### ISSUE TITLE
More info about where files are stored

### ISSUE THREAD

**Issue by piotrwitek** [wallabyjs/dingo#13]
Hey, looks like a great tool, it would be great to know where the extension is storing the downloaded files, preferably in the README. 
Thanks!

**Comment by smcenlly** [comment]
I have updated the setting description to identify that `os.tmpdir()` is used as the default if you don't specify a download directory:

https://github.com/wallabyjs/dingo/blob/4eb291dc05b396fffd1308f9dc2bcdd338f4b2d6/package.json#L39

If you think README.md update is also appropriate, please send a pull request with proposed changes.

**Comment by smcenlly** [comment]
I should also note, the setting is mentioned in the Extension feature contributions section:

<img width="1676" alt="image" src="https://user-images.githubusercontent.com/2074089/188244145-b1d2685b-d8bc-4065-872c-e4dfccf2a268.png">

**Comment by piotrwitek** [comment]
Looks good, thx
