### ISSUE TITLE
Can not open freshly created GitHub repo

### ISSUE THREAD

**Issue by ArtemGovorov** [wallabyjs/dingo#2]
- create a new GitHub repo,
- open it with Dingo,
- result:

<img width="766" alt="Screen Shot 2020-05-29 at 1 18 27 pm" src="https://user-images.githubusercontent.com/979966/83217516-4e1b9280-a1af-11ea-903f-0f0876cf20b2.png">

**Comment by smcenlly** [comment]
We've added support for opening empty repositories, see https://github.com/wallabyjs/dingo/commit/866480283eea6a2dca053219f18e430b51c79e7c.

This is available from version `1.0.7`+.
