### ISSUE TITLE
npm packages do not resolve or are missing versions

### ISSUE THREAD

**Issue by friederbluemle** [wallabyjs/dingo#4]
![image](https://user-images.githubusercontent.com/743291/83236958-46290780-a149-11ea-9fb6-00bf513cb369.png)

Using an npm package name only works with some packages (e.g. `lodash`). Others, for example `chalk`, `request` show the error message above. There are also some packages (e.g. `react`) that have a very short and incomplete version tag list. Is this a problem with npm, the extension, or my setup?

Thanks for this awesome extension!

**Comment by smcenlly** [comment]
Thanks for reporting the problem. This is fixed in the latest version, `1.0.6`.

**Comment by friederbluemle** [comment]
Awesome, thanks @smcenlly :+1:
